### ISSUE TITLE
Issue regarding ciftify results

### ISSUE THREAD

**Issue by PigeonXiong** [GongZhengxin/nodcode#1]
Hi Gongzheng,

It is great work and a nice dataset, but I had a few questions regarding ciftify results. I am not very familiar with this toolbox, so correct me if I were wrong.

In **"derivatives/ciftify/sub-XX"**, we got all surface mesh as **".surf.gii"**, they were in 32k vertices and stored according to left and right hemisphere respectively. However, all the **"dlabel.nii"** label file and fMRI beta results were in size of 59k, and got no splition for left and right hemisphere.

Is there any transformation between the 32k+32k surface mesh towards the 59k labels and results?

Regards.

**Comment by GongZhengxin** [comment]
Hi, sorry for the late,

**Why is the size 59k?**
Referring to this paper ([The minimal preprocessing pipelines for the Human Connectome Project - ScienceDirect](https://doi.org/10.1016/j.neuroimage.2013.04.127)), it is mentioned in the caption of Fig. 1: 

> Left and right cerebral cortices contribute about 30k surface vertices each (less than the 32k vertex standard meshes, because the non-cortical medial wall is masked with standard ROIs). 

In other words, vertices from the inner sides of both hemispheres (which include the corpus callosum and ventricles, as I understand) are excluded in the indexing, resulting in a total of 59k vertices remaining in the cortex.

**How to determine the relationship between cifti indices and surface vertices?**
In the fsLR32k space, each hemisphere has 32,492 vertices, and data with this shape is typically stored in Gifti format (.gii). For files like .dtseries.nii / .dlabel.nii / .dscalar.nii, you can use nibabel to retrieve vertex information from the header. Please refer to the attached code for specific implementation details ![code_1](https://github.com/GongZhengxin/NOD-fmri/assets/45821596/a049cce0-1e18-4dff-926e-3751f182a1aa) 
![code_2](https://github.com/GongZhengxin/NOD-fmri/assets/45821596/57029313-25a5-443e-82bc-768d7db75e84)
. If you are familiar with R, [this package](https://www.sciencedirect.com/science/article/pii/S1053811922000076) might be very convenient for handling cifti files (Unfortunately, I am not proficient in R).

**Comment by GongZhengxin** [comment]
besides, I would highly recommend codes from my senior co-worker: https://github.com/sunshineDrizzle/MagicBox/blob/main/magicbox/io/io.py#L164

Best of luck.
